# Dependencies
markdown:    kramdown
highlighter: rouge

# Permalinks
permalink: /:categories/:year_:month_:day_:title/


# Setup
title:        Lucas Coelho Figueiredo
tagline:     'Robotics Engineer'
description: 'Robotics engineer working for an autonomous future!'
url:          https://lucascoelho.net
baseurl:      /

author:
  name: 'Lucas Coelho Figueiredo'
  url:   https://lucascoelho.net

social_media:
  linkedin:   'https://www.linkedin.com/in/lucascoelhof/'
  github:     'https://github.com/lucascoelhof'
  email:      'lucascoelhof@gmail.com'
  instagram:  'https://instagram.com/lucascoelhof'

plugins:  [jekyll-paginate]
paginate: 5

disqusid: "lucascoelho-net.disqus.com"

# Custom vars
version: 2.1.0

github:
  repo:  https://github.com/lucascoelhof/lucascoelhof.github.io
